- Fixed a bug when starting up the ssh agent with an encrypted private key - Fixed a typo in rc-script - Updated the Installation Guide - Organized the ssh agent code into functions

diff --git a/mysql-ha/rc-script b/mysql-ha/rc-script
--- a/mysql-ha/rc-script
+++ b/mysql-ha/rc-script
@@ -59,7 +59,8 @@ start()
 	nohup su - $USER -c "cd $MYSQLHA_HOME; ./configurator.sh -p $pidf -e $encrypted>>$logf 2>&1" & >/dev/null 2>&1
 	[ -f $pidf ] && {
 		[ -d /proc/$(cat $pidf) ] && echo "OK">&2 || {
-			echo "ERROR ($(cat $pidf) does not appear to be running)">&2			return 1
+			echo "ERROR ($(cat $pidf) does not appear to be running)">&2
+			return 1
 		}
 	} || echo "ERROR ($pidf not found after nohup)">&2 && return 1
 	return 0
